/**
 *   @file  doa3dfftproc.h
 *
 *   @brief
 *      Implements doa3dfft processing functionality.
 *
 *  \par
 *  NOTE:
 *      (C) Copyright 2024 Texas Instruments, Inc.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/**************************************************************************
 *************************** Include Files ********************************
 **************************************************************************/
#ifndef DOA3D_PROC_HWA_H
#define DOA3D_PROC_HWA_H

/* Standard Include Files. */
#include <stdint.h>
#include <stdlib.h>
#include <stddef.h>
#include <string.h>
#include <stdio.h>
#include <math.h>

/* mmWave SDK Driver/Common Include Files */
#include <drivers/hwa.h>

/* DPIF Components Include Files */
#include <datapath/dpif/dpif_detmatrix.h>
#include <datapath/dpif/dpif_radarcube.h>

/* mmWave SDK Data Path Include Files */
#include <datapath/dpif/dp_error.h>


/**
@defgroup DPU_DOA_EXTERNAL_FUNCTION            doaProc DPU External Functions
@ingroup DOA_PROC_DPU
@brief
*   The section has a list of all the exported API which the applications need to
*   invoke in order to use the doaProc DPU
*/
/**
@defgroup DPU_DOA3DPROC_EXTERNAL_DATA_STRUCTURE      doaProc DPU External Data Structures
@ingroup DOA_PROC_DPU
@brief
*   The section has a list of all the data structures which are exposed to the application
*/
/**
@defgroup DPU_DOA3DPROC_ERROR_CODE                   doaProc DPU Error Codes
@ingroup DOA_PROC_DPU
@brief
*   The section has a list of all the error codes which are generated by the doaProc DPU
*/
/**
@defgroup DPU_DOPPLERPROC_INTERNAL_FUNCTION            doaProc DPU Internal Functions
@ingroup DOA_PROC_DPU
@brief
*   The section has a list of all internal API which are not exposed to the external
*   applications.
*/
/**
@defgroup DPU_DOPPLERPROC_INTERNAL_DATA_STRUCTURE      doaProc DPU Internal Data Structures
@ingroup DOA_PROC_DPU
@brief
*   The section has a list of all internal data structures which are used internally
*   by the doaProc DPU module.
*/
/**
@defgroup DPU_DOPPLERPROC_INTERNAL_DEFINITION          doaProc DPU Internal Definitions
@ingroup DOA_PROC_DPU
@brief
*   The section has a list of all internal definitions which are used internally
*   by the doaProc DPU.
*/

#ifdef __cplusplus
extern "C" {
#endif

/** @addtogroup DPU_DOA3DPROC_ERROR_CODE
 *  Base error code for the dopplerProc DPU is defined in the
 *  \include ti/datapath/dpif/dp_error.h
 @{ */

#define DP_ERRNO_DOA3D_PROC_BASE            (MMWAVE_ERRNO_DPU_BASE -1400)

/**
 * @brief   Error Code: Invalid argument
 */
#define DPU_DOA3DPROC_EINVAL                  (DP_ERRNO_DOA3D_PROC_BASE-1)

/**
 * @brief   Error Code: Out of memory
 */
#define DPU_DOA3DPROC_ENOMEM                  (DP_ERRNO_DOA3D_PROC_BASE-2)

/**
 * @brief   Error Code: DPU is in progress
 */
#define DPU_DOA3DPROC_EINPROGRESS             (DP_ERRNO_DOA3D_PROC_BASE-3)

/**
 * @brief   Error Code: Out of HWA resources
 */
#define DPU_DOA3DPROC_EHWARES                 (DP_ERRNO_DOA3D_PROC_BASE-4)

/**
 * @brief   Error Code: Semaphore creation failed
 */
#define DPU_DOA3DPROC_ESEMA                   (DP_ERRNO_DOA3D_PROC_BASE-5)

/**
 * @brief   Error Code: Bad semaphore status 
 */
#define DPU_DOA3DPROC_ESEMASTATUS             (DP_ERRNO_DOA3D_PROC_BASE-6)

/**
 * @brief   Error Code: Configure parameters exceed HWA memory bank size 
 */
#define DPU_DOA3DPROC_EEXCEEDHWAMEM           (DP_ERRNO_DOA3D_PROC_BASE-7)

/**
 * @brief   Error Code: Unsupported radar cube format 
 */
#define DPU_DOA3DPROC_ECUBEFORMAT             (DP_ERRNO_DOA3D_PROC_BASE-8)

/**
 * @brief   Error Code: Unsupported detection matrix format 
 */
#define DPU_DOA3DPROC_EDETMFORMAT             (DP_ERRNO_DOA3D_PROC_BASE-9)

/**
 * @brief   Error Code: Insufficient detection matrix size
 */
#define DPU_DOA3DPROC_EDETMSIZE               (DP_ERRNO_DOA3D_PROC_BASE-10)

/**
 * @brief   Error Code: Wrong window size
 */
#define DPU_DOA3DPROC_EWINDSIZE               (DP_ERRNO_DOA3D_PROC_BASE-11)

/**
 * @brief   Error Code: Insufficient memory to save HWA param sets
 */
#define DPU_DOA3DPROC_EHWA_PARAM_SAVE_LOC_SIZE (DP_ERRNO_DOA3D_PROC_BASE-12)

/**
 * @brief   Error Code: Not supported angle dim 1 (no elevation) and
 */
#define DPU_DOA3DPROC_E_NOTSUPPORTED_ANGLE_DIM_ONE_AND_CPU_LOOP_CTRL (DP_ERRNO_DOA3D_PROC_BASE-13)

/**
 * @brief   Error Code: Doppler FFT size exceeded the limit. Maximum Doppler index is stored in array of type uint8_t.
 */
#define DPU_DOA3DPROC_E_EXCEEDED_MAX_NUM_DOPPLER_BINS (DP_ERRNO_DOA3D_PROC_BASE-14)


/**
 * @brief   Maximum number of HWA param sets used by DPU.
 */
#define DPU_DOA3DPROC_MAX_NUM_HWA_PARAMSET  16

/**
 * @brief   Number of HWA memory banks needed
 */
#define DPU_DOA3DPROC_NUM_HWA_MEMBANKS  4 

/**
 * @brief   Disables first butterfly stage scaling
 */
#define DPU_DOA3DPROC_FIRST_SCALING_DISABLED ((uint8_t)0U)

/**
 * @brief   Enables first butterfly stage scaling
 */
#define DPU_DOA3DPROC_FIRST_SCALING_ENABLED ((uint8_t)1U)



/**
 * @brief
 *  doaProc DPU EDMA configuration parameters
 *
 * @details
 *  The structure is used to hold the EDMA configuration parameters
 *  for the Doppler Processing DPU
 *
 *  \ingroup DPU_DOA3DPROC_EXTERNAL_DATA_STRUCTURE
 */
typedef struct DPU_Doa3dProc_Edma_t
{
    /*! @brief  EDMA channels for circular to linear copy */
    DPEDMA_ChanCfg  chunk[2];

}DPU_Doa3dProc_Edma;


/**
 * @brief
 *  doaProc DPU statistics
 *
 * @details
 *  The structure is used to hold the statistics of the DPU 
 *
 *  \ingroup DPU_DOA3DPROC_EXTERNAL_DATA_STRUCTURE
 */
typedef struct DPU_Doa3dProc_Stats_t
{
    /*! @brief total number of DPU processing */
    uint32_t            numProcess;

    /*! @brief For HWA version of the DPU: total processing time including EDMA transfers.\n
               For DSP version of the DPU: total processing time excluding EDMA transfers.*/
    uint32_t            processingTime;
    
    /*! @brief time spent waiting for EDMA transfers. Valid only for DSP version of DPU.*/
    uint32_t            waitTime;
}DPU_Doa3dProc_Stats;


/**
* @brief
*  Source and destination addresses for EDMA input configuration. 
*
* @details
*  The structure is one of the input arguments of the DPU's proces function.
*
*  \ingroup DPU_AOAPROC_EXTERNAL_DATA_STRUCTURE
*/
typedef struct DPU_Doa3dProc_RadarCubeChunkEdmaCfg_t
{
    /*! @brief     Address in L3 of the chunk of data in radar cube matrix to be copied to HWA  */
    uint32_t srcAddress;

    /*! @brief     Destination address in HWA of the copied chunk */
    uint32_t dstAddress;

    /*! @brief     Packed EDMA values for A count (LSB 16-bit position) and B count (MSB 16-bit position */
    uint32_t Bcnt_Acnt;
} DPU_Doa3dProc_RadarCubeChunkEdmaCfg;

typedef struct DPU_Doa3dProc_RadarCubeSource_t
{
    DPU_Doa3dProc_RadarCubeChunkEdmaCfg chunk[2];
} DPU_Doa3dProc_RadarCubeSource;

/*!
 *  @brief   Handle for Doppler Processing DPU.
 */
typedef void*  DPU_Doa3dProc_Handle;

/**
 * @brief
 *  dopplerProc DPU initial configuration parameters
 *
 * @details
 *  The structure is used to hold the DPU initial configurations.
 *
 *  \ingroup DPU_DOA3DPROC_EXTERNAL_DATA_STRUCTURE
 */
typedef struct DPU_Doa3dProc_InitCfg_t
{
    HWA_Handle  hwaHandle;
    
}DPU_Doa3dProc_InitParams;

/**
 * @brief
 *  Configuration parameters for each HWA param set performing the Doppler FFTs and mappng output into
 *  row-col array as input to azimuth/elevation FFTs
 *
 * @details
 * Input antenna format to Doppler FFTs per range bin is X[antInd][chirpInd]
 * Output antenna format is Y[dopplerInd][rowInd][colInd]
 * HWA param set can perform only fixed source and destination increment (B dimension)
 *
 */
typedef struct DPU_Doa3dProc_HWA_Doppler_Fft_Cfg_t
{
    /*! @brief   Number of input columns (doppler FFTs) in the input matrix to process */
    uint16_t    srcBcnt;

    /*! @brief   Column offset in the input matrix */
    int16_t     srcAddrOffset;

    /*! @brief  column increment in number of columns in source matrix */
    int16_t     srcBidx;

    /*! @brief   Scale in pre compensation */
    int16_t     scale;

    /*! @brief  column/row offset in the destination matrix dstAddrOffset = colOffset + rowOffset*numColumns */
    int16_t     dstAddrOffset;

    /*! @brief  column increment in number of columns in destination matrix */
    int16_t     dstBidx;
} DPU_Doa3dProc_HWA_Doppler_Fft_Cfg;

/**
 * @brief    Maximum nuber of Doppler FFT params
 *
 */
#define DPU_DOA3DPROC_MAX_NUM_DOP_FFFT_PARAMS 8

/**
 * @brief    Maximum number of antenna elements in 2D virtual antenna array (maximum value of the product numRows*numCol)
 *
 */
#define DPU_DOA_PROC_MAX_2D_ANT_ARRAY_ELEMENTS 16

/**
 * @brief
 *
 */
typedef struct DPU_Doa3dProc_HWA_Option_Cfg_t
{
    uint8_t numDopFftParams;
    DPU_Doa3dProc_HWA_Doppler_Fft_Cfg dopFftCfg[DPU_DOA3DPROC_MAX_NUM_DOP_FFFT_PARAMS];
} DPU_Doa3dProc_HWA_Option_Cfg;

/**
 * @brief
 *  Structure for the HWA Params save location
 *
 *
 *  \ingroup DPU_DOA3DPROC_EXTERNAL_DATA_STRUCTURE
 */
typedef struct DPU_Doa3dProc_HwaParamSaveLoc_t
{
    /*! @brief  Pointer to save location for HWA PARAM sets */
    void        *data;

    /*! @brief  Size of the save location for HWA PARAM sets in Bytes*/
    uint32_t    sizeBytes;
} DPU_Doa3dProc_HwaParamSaveLoc;

/**
 * @brief
 *  dopplerProc DPU HWA configuration parameters
 *
 * @details
 *  The structure is used to hold the HWA configuration parameters
 *  for the Doppler Processing DPU
 *
 *  \ingroup DPU_DOA3DPROC_EXTERNAL_DATA_STRUCTURE
 */
typedef struct DPU_Doa3dProc_HwaCfg_t
{
    /*! @brief Indicates if HWA window is symmetric or non-symmetric.
        Use HWA macro definitions for symmetric/non-symmetric.
    */
    uint8_t     winSym;

    /*!  @brief Doppler FFT window size in bytes. 
         This is the number of coefficients to be programmed in the HWA for the windowing
         functionality. The size is a function of numDopplerChirps as follows:\n
         If non-symmetric window is selected: windowSize = numDopplerChirps * sizeof(int32_t) \n
         If symmetric window is selected and numDopplerChirps is even:
         windowSize = numDopplerChirps * sizeof(int32_t) / 2 \n
         If symmetric window is selected and numDopplerChirps is odd:
         windowSize = (numDopplerChirps + 1) * sizeof(int32_t) / 2        
    */
    uint32_t    windowSize;

    /*! @brief Pointer to Doppler FFT window coefficients. */
    int32_t     *window;

    /*! @brief HWA window RAM offset in number of samples. */
    uint32_t    winRamOffset;
    
    /*! @brief Indicates if HWA should enable butterfly scaling (divide by 2) of the 
         first radix-2 stage. Depending on the window definition, 
         user may want to skip the first stage scaling in order to avoid signal degradation.\n
         Options are:\n
         Disable first stage scaling: firstStageScaling = @ref DPU_DOA3DPROC_FIRST_SCALING_DISABLED \n
         Enable first stage scaling: firstStageScaling = @ref DPU_DOA3DPROC_FIRST_SCALING_ENABLED \n
         Note: All other butterfly stages have the scaling enabled. 
         This option applies only for the first stage.\n
    */
    uint8_t     firstStageScaling;

    /*! @brief Number of HWA paramsets reserved for the Doppler DPU. 
         The number of HWA paramsets required by this DPU is a function of the number of TX antennas 
         used in the configuration:\n 
         numParamSets = 2 x (Number of TX antennas) + 2\n
         The DPU will use numParamSets consecutively, starting from paramSetStartIdx.\n
    */     
    uint8_t     numParamSets;
    
    /*! @brief HWA paramset Start index.  
         Application has to ensure that paramSetStartIdx is such that \n
        [paramSetStartIdx, paramSetStartIdx + 1, ... (paramSetStartIdx + numParamSets - 1)] \n
        is a valid set of HWA paramsets.\n
    */
    uint32_t    paramSetStartIdx;

    /*! @brief HWA data input paramset dma trigger source channel
    */
    uint8_t dmaTrigSrcChan;

    /*! @brief HWA Params save location
    */
    DPU_Doa3dProc_HwaParamSaveLoc hwaParamsSaveLoc;

    /*! @brief HWA Doppler FFT Parmas set configuration (performing Doppler FFT and antenna mapping)
    */
    DPU_Doa3dProc_HWA_Option_Cfg doaRngGateCfg;


}DPU_Doa3dProc_HwaCfg;

/*!
 *  @brief    Maximum peaks filled by HWA statistics block
 *
 *  \ingroup DPU_DOA3DPROC_EXTERNAL_DATA_STRUCTURE
 *
 */
typedef volatile struct DPU_Doa3dProc_HwaMaxOutput_t
{
    uint32_t   maxInd;      /*!< @brief Maximum peak index position */
    uint32_t   peak;        /*!< @brief Maximum peak value */
}  DPU_Doa3dProc_HwaMaxOutput;


/**
 * @brief
 *  dopplerProc DPU EDMA configuration parameters
 *
 * @details
 *  The structure is used to hold the EDMA configuration parameters
 *  for the Doppler Processing DPU
 *
 *  \ingroup DPU_DOA3DPROC_EXTERNAL_DATA_STRUCTURE
 */
typedef struct DPU_Doa3dProc_EdmaCfg_t
{
    /*! @brief  EDMA driver handle. */
    EDMA_Handle edmaHandle;
    uint32_t    edmaInstanceId;
    
    /*! @brief  EDMA configuration for Input data (Radar cube -> HWA memory). */
    DPU_Doa3dProc_Edma edmaIn;

    /*! @brief  EDMA configuration for hot signature. */
    DPEDMA_ChanCfg edmaHotSig;
    
    /*! @brief  EDMA configuration for data output from HWA - Detection matrix */
    DPEDMA_ChanCfg edmaDetMatOut;
    /*! @brief  EDMA configuration for data output from HWA - Doppler Index matrix */
    DPEDMA_ChanCfg dopIndMatOut;
    /*! @brief  EDMA configuration for data output from HWA - Elevation index matrix */
    DPEDMA_ChanCfg elevIndMatOut;

    /*! @brief  EDMA configuration for data output  */
    DPEDMA_ChanCfg edmaInterLoopOut;
    /*! @brief  EDMA configuration for data in */
    DPEDMA_ChanCfg edmaInterLoopIn;
    /*! @brief  EDMA configuration for hot signature. */
    DPEDMA_ChanCfg edmaInterLoopHotSig;
    /*! @brief  EDMA configuration for loop chain back. */
    DPEDMA_ChanCfg edmaInterLoopChainBack;

}DPU_Doa3dProc_EdmaCfg;

/**
 * @brief
 *  Doppler DPU HW configuration parameters
 *
 * @details
 *  The structure is used to hold the  HW configuration parameters
 *  for the Doppler DPU
 *
 *  \ingroup DPU_DOA3DPROC_EXTERNAL_DATA_STRUCTURE
 */
typedef struct DPU_Doa3dProc_HW_Resources_t
{
    /*! @brief  EDMA configuration */
    DPU_Doa3dProc_EdmaCfg edmaCfg;
    
    /*! @brief  HWA configuration */
    DPU_Doa3dProc_HwaCfg  hwaCfg;
    
    /*! @brief  Radar Cube */
    DPIF_RadarCube radarCube;
    
    /*! @brief  Detection matrix */
    DPIF_DetMatrix detMatrix;

    /*! @brief  Doppler index matrix */
    DPIF_DetMatrix dopplerIndexMatrix;

}DPU_Doa3dProc_HW_Resources;

/**
 * @brief Range Bias and rx channel gain/phase compensation configuration.
 *
 *
 *  \ingroup    DPU_DOA3DPROC_EXTERNAL_DATA_STRUCTURE
 *
 */
typedef struct DPU_Doa3dProc_compRxChannelBiasCfg_t
{

    /*! @brief  Compensation for range estimation bias in meters */
    float rangeBias;

    /*! @brief  Compensation for Rx channel phase bias in Q20 format.
     *          The order here is like x[tx][rx] where rx order is 0,1,....SYS_COMMON_NUM_RX_CHANNEL-1
     *          and tx order is 0, 1,...,SYS_COMMON_NUM_TX_ANTENNAS-1 */
    cmplx32ReIm_t rxChPhaseComp[SYS_COMMON_NUM_TX_ANTENNAS * SYS_COMMON_NUM_RX_CHANNEL];

} DPU_Doa3dProc_compRxChannelBiasCfg;

/**
 * @brief
 *  Doppler DPU static configuration parameters
 *
 * @details
 *  The structure is used to hold the static configuration parameters
 *  for the Doppler DPU. The following conditions must be satisfied:
 *
 *    @verbatim
      numTxAntennas * numRxAntennas * numDopplerChirps * sizeof(cmplx16ImRe_t) <= 16 KB (one HWA memory bank)
      numTxAntennas * numRxAntennas * numDopplerBins * sizeof(uint16_t) <= 16 KB (one HWA memory bank)
      @endverbatim
 *
 *  \ingroup DPU_DOA3DPROC_EXTERNAL_DATA_STRUCTURE
 */
typedef struct DPU_Doa3dProc_StaticConfig_t
{
    /*! @brief  Number of transmit antennas */
    uint8_t     numTxAntennas;
    
    /*! @brief  Number of receive antennas */
    uint8_t     numRxAntennas;
    
    /*! @brief  Number of virtual antennas */
    uint8_t     numVirtualAntennas; 
    
    /*! @brief  Number of range bins */
    uint16_t    numRangeBins;
    
    /*! @brief  Number of Doppler chirps. */
    uint16_t    numDopplerChirps;
    
    /*! @brief  Number of Doppler bins */
    uint16_t    numDopplerBins;
    
    /*! @brief  Azimuth FFT size */
    uint16_t    azimuthFftSize;

    /*! @brief  elevation FFT size */
    uint16_t    elevationFftSize;

    /*! @brief  Log2 of number of Doppler bins */
    uint8_t     log2NumDopplerBins;
    
    /*! @brief     1 - select the coherent peak in Doppler, 
                   0 - non-coherently combine accross Doppler, zero doppler output,
                   2 - non-coherently combine accross Doppler, doppler output based on Doppler maximum position */
    uint8_t        selectCoherentPeakInDopplerDim;

    /*! @brief     1 - 1D: 6x1 azimuth antenna array 2 - 2D: one lower row: 4 antennas, upper row 2 antennas */
    uint8_t     angleDimension;

    /*! @brief     Detection matrix format 0 - Linear 32-bit integer, 1 - 16-bit log2 magnitude in Q11 format */
    bool        isDetMatrixLogScale;

    /*! @brief   Static Clutter Removal Cfg */
    bool        isStaticClutterRemovalEnabled;

    /*! @brief   Range Bias and rx channel gain/phase compensation enable flag */
    bool        isRxChGainPhaseCompensationEnabled;

    /*! @brief   Range Bias and rx channel gain/phase compensation configuration */
    DPU_Doa3dProc_compRxChannelBiasCfg compRxChanCfg;

    uint16_t numAntRow;
    uint16_t numAntCol;

    /*! @brief     Load HWA params sets before execution */
    bool loadHwaParamSetsBeforeExec;

}DPU_Doa3dProc_StaticConfig;

/**
 * @brief
 *  dopplerProc DPU configuration parameters
 *
 * @details
 *  The structure is used to hold the configuration parameters
 *  for the Doppler Processing removal DPU
 *
 *  \ingroup DPU_DOA3DPROC_EXTERNAL_DATA_STRUCTURE
 */
typedef struct DPU_Doa3dProc_Config_t
{
    /*! @brief HW resources. */
    DPU_Doa3dProc_HW_Resources  hwRes;
    
    /*! @brief Static configuration. */
    DPU_Doa3dProc_StaticConfig  staticCfg;
    
}DPU_Doa3dProc_Config;


/**
 * @brief
 *  DPU processing output parameters
 *
 * @details
 *  The structure is used to hold the output parameters DPU processing
 *
 *  \ingroup DPU_DOA3DPROC_EXTERNAL_DATA_STRUCTURE
 */
typedef struct DPU_Doa3dProc_OutParams_t
{
    /*! @brief DPU statistics */
    DPU_Doa3dProc_Stats  stats;
}DPU_Doa3dProc_OutParams;


DPU_Doa3dProc_Handle DPU_Doa3dProc_init(DPU_Doa3dProc_InitParams *initCfg, int32_t* errCode);
int32_t DPU_Doa3dProc_process(DPU_Doa3dProc_Handle handle, DPU_Doa3dProc_OutParams *outParams);
int32_t DPU_Doa3dProc_deinit(DPU_Doa3dProc_Handle handle);
int32_t DPU_Doa3dProc_config(DPU_Doa3dProc_Handle handle, DPU_Doa3dProc_Config *cfg);
int32_t DPU_Doa3dProc_GetNumUsedHwaParamSets(DPU_Doa3dProc_Handle handle, uint8_t *numUsedHwaParamSets);

#if 0
int32_t DPU_DoaProcHWA_control
(
   DPU_AoAProcHWA_Handle handle,
   DPU_AoAProcHWA_Cmd cmd,
   void *arg,
   uint32_t argSize
);
#endif


#ifdef __cplusplus
}
#endif

#endif
