/*
 * Copyright (C) 2022-24 Texas Instruments Incorporated
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *   Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 *   Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in the
 *   documentation and/or other materials provided with the
 *   distribution.
 *
 *   Neither the name of Texas Instruments Incorporated nor the names of
 *   its contributors may be used to endorse or promote products derived
 *   from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
#ifndef MMW_DEMO_RES_H
#define MMW_DEMO_RES_H

#ifdef __cplusplus
extern "C" {
#endif

#include <drivers/edma.h>
#include <drivers/hw_include/cslr_soc.h>

/*******************************************************************************
 * Resources for Object Detection DPC, currently the only DPC and hwa/edma
 * resource used in the demo.
 *******************************************************************************/
#define EDMA_NUM_DMA_CHANNELS                                               (SOC_EDMA_NUM_DMACH/2)  //In xwrL68xx there are no shadow channels so free channels are used

#define DPC_OBJDET_EDMA_SHADOW_BASE                                       16//  EDMA_NUM_DMA_CHANNELS

/* Range DPU */
#define DPC_OBJDET_DPU_RANGEPROC_PARAMSET_START_IDX 0
#define DPC_OBJDET_DPU_RANGEPROC_EDMA_INST_ID         0
#define DPC_OBJDET_DPU_RANGEPROC_EDMAIN_CH            EDMA_DSS_TPCC_A_CHIRP_AVAIL_IRQ
#define DPC_OBJDET_DPU_RANGEPROC_EDMAIN_SHADOW        (DPC_OBJDET_EDMA_SHADOW_BASE + 0)
#define DPC_OBJDET_DPU_RANGEPROC_EDMAIN_EVENT_QUE     0
#define DPC_OBJDET_DPU_RANGEPROC_EDMAIN_SIG_CH        (EDMA_DSS_TPCC_A_EVT_FREE_0 + 0)
#define DPC_OBJDET_DPU_RANGEPROC_EDMAIN_SIG_SHADOW    (DPC_OBJDET_EDMA_SHADOW_BASE + 1)
#define DPC_OBJDET_DPU_RANGEPROC_EDMAIN_SIG_EVENT_QUE 0

/* FMT1 EDMA resources */

#define DPC_OBJDET_DPU_RANGEPROC_EDMAOUT_FMT1_PING_CH        EDMA_DSS_TPCC_A_EVT_DSS_HW_ACC_CHANNEL_TRIGGER_0
#define DPC_OBJDET_DPU_RANGEPROC_EDMAOUT_FMT1_PING_SHADOW    (DPC_OBJDET_EDMA_SHADOW_BASE + 2)
#define DPC_OBJDET_DPU_RANGEPROC_EDMAOUT_FMT1_PING_EVENT_QUE 0

#define DPC_OBJDET_DPU_RANGEPROC_EDMAOUT_FMT1_PONG_CH        EDMA_DSS_TPCC_A_EVT_DSS_HW_ACC_CHANNEL_TRIGGER_1
#define DPC_OBJDET_DPU_RANGEPROC_EDMAOUT_FMT1_PONG_SHADOW    (DPC_OBJDET_EDMA_SHADOW_BASE + 3)
#define DPC_OBJDET_DPU_RANGEPROC_EDMAOUT_FMT1_PONG_EVENT_QUE 0

#define DPC_OBJDET_DPU_RANGEPROC_EDMAOUT_SIG_CH        (EDMA_DSS_TPCC_A_EVT_FREE_1 + 0)
#define DPC_OBJDET_DPU_RANGEPROC_EDMAOUT_SIG_SHADOW    (DPC_OBJDET_EDMA_SHADOW_BASE + 4)
#define DPC_OBJDET_DPU_RANGEPROC_EDMAOUT_SIG_EVENT_QUE 0

/* DoA DPU */
#define DPC_OBJDET_DPU_DOAPROC_EDMA_INST_ID                           0

#define DPC_OBJDET_DPU_DOAPROC_EDMAIN_PING_CH                         (EDMA_DSS_TPCC_A_EVT_FREE_2 + 0)
#define DPC_OBJDET_DPU_DOAPROC_EDMAIN_PING_SHADOW                     (DPC_OBJDET_EDMA_SHADOW_BASE + 5)
#define DPC_OBJDET_DPU_DOAPROC_EDMAIN_PING_EVENT_QUE                  0

#define DPC_OBJDET_DPU_DOAPROC_EDMAIN_PONG_CH                         (EDMA_DSS_TPCC_A_EVT_FREE_3 + 0)
#define DPC_OBJDET_DPU_DOAPROC_EDMAIN_PONG_SHADOW                     (DPC_OBJDET_EDMA_SHADOW_BASE + 6)
#define DPC_OBJDET_DPU_DOAPROC_EDMAIN_PONG_EVENT_QUE                  0

#define DPC_OBJDET_DPU_DOAPROC_EDMA_HOT_SIG_CH                        (EDMA_DSS_TPCC_A_EVT_FREE_4 + 0)
#define DPC_OBJDET_DPU_DOAPROC_EDMA_HOT_SIG_SHADOW                    (DPC_OBJDET_EDMA_SHADOW_BASE + 7)
#define DPC_OBJDET_DPU_DOAPROC_EDMA_HOT_SIG_EVENT_QUE                 0

#define DPC_OBJDET_DPU_DOAPROC_EDMAOUT_DET_MATRIX_CH                  EDMA_DSS_TPCC_A_EVT_DSS_HW_ACC_CHANNEL_TRIGGER_2
#define DPC_OBJDET_DPU_DOAPROC_EDMAOUT_DET_MATRIX_SHADOW              (DPC_OBJDET_EDMA_SHADOW_BASE + 8)
#define DPC_OBJDET_DPU_DOAPROC_EDMAOUT_DET_MATRIX_EVENT_QUE           0

#define DPC_OBJDET_DPU_DOAPROC_EDMAOUT_ELEVIND_MATRIX_CH              (EDMA_DSS_TPCC_A_EVT_FREE_5 + 0)
#define DPC_OBJDET_DPU_DOAPROC_EDMAOUT_ELEVIND_MATRIX_SHADOW          (DPC_OBJDET_EDMA_SHADOW_BASE + 9)
#define DPC_OBJDET_DPU_DOAPROC_EDMAOUT_ELEVIND_MATRIX_EVENT_QUE       0

#define DPC_OBJDET_DPU_DOAPROC_EDMAOUT_DOPIND_MATRIX_CH               (EDMA_DSS_TPCC_A_EVT_FREE_6 + 0)
#define DPC_OBJDET_DPU_DOAPROC_EDMAOUT_DOPIND_MATRIX_SHADOW           (DPC_OBJDET_EDMA_SHADOW_BASE + 10)
#define DPC_OBJDET_DPU_DOAPROC_EDMAOUT_DOPIND_MATRIX_EVENT_QUE        0

#define DPC_OBJDET_DPU_DOAPROC_INTER_LOOP_EDMAOUT_DET_MATRIX_CH          EDMA_DSS_TPCC_A_EVT_DSS_HW_ACC_CHANNEL_TRIGGER_3
#define DPC_OBJDET_DPU_DOAPROC_INTER_LOOP_EDMAOUT_DET_MATRIX_SHADOW      (DPC_OBJDET_EDMA_SHADOW_BASE + 11)
#define DPC_OBJDET_DPU_DOAPROC_INTER_LOOP_EDMAOUT_DET_MATRIX_EVENT_QUE   0

#define DPC_OBJDET_DPU_DOAPROC_INTER_LOOP_EDMAIN_CH                      (EDMA_DSS_TPCC_A_EVT_FREE_7 + 0)
#define DPC_OBJDET_DPU_DOAPROC_INTER_LOOP_EDMAIN_SHADOW                  (DPC_OBJDET_EDMA_SHADOW_BASE + 12)
#define DPC_OBJDET_DPU_DOAPROC_INTER_LOOP_EDMAIN_EVENT_QUE               0

#define DPC_OBJDET_DPU_DOAPROC_INTER_LOOP_EDMA_HOT_SIG_CH                (EDMA_DSS_TPCC_A_EVT_FREE_8 + 0)
#define DPC_OBJDET_DPU_DOAPROC_INTER_LOOP_EDMA_HOT_SIG_SHADOW            (DPC_OBJDET_EDMA_SHADOW_BASE + 13)
#define DPC_OBJDET_DPU_DOAPROC_INTER_LOOP_EDMA_HOT_SIG_EVENT_QUE         0

#define DPC_OBJDET_DPU_DOAPROC_INTER_LOOP_EDMA_CHAIN_BACK_CH             (EDMA_DSS_TPCC_A_EVT_FREE_9 + 0)
#define DPC_OBJDET_DPU_DOAPROC_INTER_LOOP_EDMA_CHAIN_BACK_SHADOW         (DPC_OBJDET_EDMA_SHADOW_BASE + 14)
#define DPC_OBJDET_DPU_DOAPROC_INTER_LOOP_EDMA_CHAIN_BACK_EVENT_QUE      0

/* SNR3DHM DPU */
#define DPC_OBJDET_DPU_SNR3D_PROC_EDMA_INST_ID                           0

#define DPC_OBJDET_DPU_SNR3D_PROC_EDMAIN_PING_CH                          (EDMA_DSS_TPCC_A_EVT_FREE_10 + 0)
#define DPC_OBJDET_DPU_SNR3D_PROC_EDMAIN_PING_SHADOW                      (DPC_OBJDET_EDMA_SHADOW_BASE + 15)
#define DPC_OBJDET_DPU_SNR3D_PROC_EDMAIN_PING_EVENT_QUE                   0

#define DPC_OBJDET_DPU_SNR3D_PROC_EDMAIN_PING_SIG_CH                      (EDMA_DSS_TPCC_A_EVT_FREE_11 + 0)
#define DPC_OBJDET_DPU_SNR3D_PROC_EDMAIN_PING_SIG_SHADOW                  (DPC_OBJDET_EDMA_SHADOW_BASE + 16)
#define DPC_OBJDET_DPU_SNR3D_PROC_EDMAIN_PING_SIG_EVENT_QUE               0

#define DPC_OBJDET_DPU_SNR3D_PROC_EDMAOUT_PING_CH                         EDMA_DSS_TPCC_A_EVT_DSS_HW_ACC_CHANNEL_TRIGGER_4
#define DPC_OBJDET_DPU_SNR3D_PROC_EDMAOUT_PING_SHADOW                     (DPC_OBJDET_EDMA_SHADOW_BASE + 17)
#define DPC_OBJDET_DPU_SNR3D_PROC_EDMAOUT_PING_EVENT_QUE                  0

#define DPC_OBJDET_DPU_SNR3D_PROC_EDMAIN_PONG_CH                          (EDMA_DSS_TPCC_A_EVT_FREE_12 + 0)
#define DPC_OBJDET_DPU_SNR3D_PROC_EDMAIN_PONG_SHADOW                      (DPC_OBJDET_EDMA_SHADOW_BASE + 18)
#define DPC_OBJDET_DPU_SNR3D_PROC_EDMAIN_PONG_EVENT_QUE                   0

#define DPC_OBJDET_DPU_SNR3D_PROC_EDMAIN_PONG_SIG_CH                      (EDMA_DSS_TPCC_A_EVT_FREE_13 + 0)
#define DPC_OBJDET_DPU_SNR3D_PROC_EDMAIN_PONG_SIG_SHADOW                  (DPC_OBJDET_EDMA_SHADOW_BASE + 19)
#define DPC_OBJDET_DPU_SNR3D_PROC_EDMAIN_PONG_SIG_EVENT_QUE               0

#define DPC_OBJDET_DPU_SNR3D_PROC_EDMAOUT_PONG_CH                         EDMA_DSS_TPCC_A_EVT_DSS_HW_ACC_CHANNEL_TRIGGER_5
#define DPC_OBJDET_DPU_SNR3D_PROC_EDMAOUT_PONG_SHADOW                     (DPC_OBJDET_EDMA_SHADOW_BASE + 20)
#define DPC_OBJDET_DPU_SNR3D_PROC_EDMAOUT_PONG_EVENT_QUE                  0

/* MacroDoppler DPU */
#define DPC_OBJDET_DPU_MACRODOPP_DCEST_PROC_EDMA_INST_ID                       0

//chirp DC estimation
#define DPC_OBJDET_DPU_MACRODOPP_DCEST_EDMAIN_PING_CH                          (EDMA_DSS_TPCC_A_EVT_FREE_2 + 0)
#define DPC_OBJDET_DPU_MACRODOPP_DCEST_EDMAIN_PING_SHADOW                      (DPC_OBJDET_EDMA_SHADOW_BASE + 5)
#define DPC_OBJDET_DPU_MACRODOPP_DCEST_EDMAIN_PING_EVENT_QUE                   0

#define DPC_OBJDET_DPU_MACRODOPP_DCEST_EDMAIN_PING_SIG_CH                      (EDMA_DSS_TPCC_A_EVT_FREE_3 + 0)
#define DPC_OBJDET_DPU_MACRODOPP_DCEST_EDMAIN_PING_SIG_SHADOW                  (DPC_OBJDET_EDMA_SHADOW_BASE + 6)
#define DPC_OBJDET_DPU_MACRODOPP_DCEST_EDMAIN_PING_SIG_EVENT_QUE               0

#define DPC_OBJDET_DPU_MACRODOPP_DCEST_EDMAOUT_PING_CH                         EDMA_DSS_TPCC_A_EVT_DSS_HW_ACC_CHANNEL_TRIGGER_2
#define DPC_OBJDET_DPU_MACRODOPP_DCEST_EDMAOUT_PING_SHADOW                     (DPC_OBJDET_EDMA_SHADOW_BASE + 7)
#define DPC_OBJDET_DPU_MACRODOPP_DCEST_EDMAOUT_PING_EVENT_QUE                  0

#define DPC_OBJDET_DPU_MACRODOPP_DCEST_EDMAIN_PONG_CH                          (EDMA_DSS_TPCC_A_EVT_FREE_4 + 0)
#define DPC_OBJDET_DPU_MACRODOPP_DCEST_EDMAIN_PONG_SHADOW                      (DPC_OBJDET_EDMA_SHADOW_BASE + 8)
#define DPC_OBJDET_DPU_MACRODOPP_DCEST_EDMAIN_PONG_EVENT_QUE                   0

#define DPC_OBJDET_DPU_MACRODOPP_DCEST_EDMAIN_PONG_SIG_CH                      (EDMA_DSS_TPCC_A_EVT_FREE_5 + 0)
#define DPC_OBJDET_DPU_MACRODOPP_DCEST_EDMAIN_PONG_SIG_SHADOW                  (DPC_OBJDET_EDMA_SHADOW_BASE + 9)
#define DPC_OBJDET_DPU_MACRODOPP_DCEST_EDMAIN_PONG_SIG_EVENT_QUE               0

#define DPC_OBJDET_DPU_MACRODOPP_DCEST_EDMAOUT_PONG_CH                         EDMA_DSS_TPCC_A_EVT_DSS_HW_ACC_CHANNEL_TRIGGER_3
#define DPC_OBJDET_DPU_MACRODOPP_DCEST_EDMAOUT_PONG_SHADOW                     (DPC_OBJDET_EDMA_SHADOW_BASE + 10)
#define DPC_OBJDET_DPU_MACRODOPP_DCEST_EDMAOUT_PONG_EVENT_QUE                  0

//Bartlett beamforming
#define DPC_OBJDET_DPU_MACRODOPP_BBF_EDMA_CHIRP_IN_CH                          (EDMA_DSS_TPCC_A_EVT_FREE_6 + 0)
#define DPC_OBJDET_DPU_MACRODOPP_BBF_EDMA_CHIRP_IN_SHADOW                      (DPC_OBJDET_EDMA_SHADOW_BASE + 11)
#define DPC_OBJDET_DPU_MACRODOPP_BBF_EDMA_CHIRP_IN_EVENT_QUE                   0

#define DPC_OBJDET_DPU_MACRODOPP_BBF_EDMA_CHIRPDC_IN_CH                        (EDMA_DSS_TPCC_A_EVT_FREE_7 + 0)
#define DPC_OBJDET_DPU_MACRODOPP_BBF_EDMA_CHIRPDC_IN_SHADOW                    (DPC_OBJDET_EDMA_SHADOW_BASE + 12) 
#define DPC_OBJDET_DPU_MACRODOPP_BBF_EDMA_CHIRPDC_IN_EVENT_QUE                 0

#define DPC_OBJDET_DPU_MACRODOPP_BBF_EDMA_STEERVEC_IN_CH                       (EDMA_DSS_TPCC_A_EVT_FREE_8 + 0)
#define DPC_OBJDET_DPU_MACRODOPP_BBF_EDMA_STEERVEC_IN_SHADOW                   (DPC_OBJDET_EDMA_SHADOW_BASE + 13)
#define DPC_OBJDET_DPU_MACRODOPP_BBF_EDMA_STEERVEC_IN_EVENT_QUE                0


#define DPC_OBJDET_DPU_MACRODOPP_BBF_EDMA_HOTSIG_CH                            (EDMA_DSS_TPCC_A_EVT_FREE_9 + 0)
#define DPC_OBJDET_DPU_MACRODOPP_BBF_EDMA_HOTSIG_SHADOW                        (DPC_OBJDET_EDMA_SHADOW_BASE + 14)
#define DPC_OBJDET_DPU_MACRODOPP_BBF_EDMA_HOTSIG_EVENT_QUE                     0

#define DPC_OBJDET_DPU_MACRODOPP_BBF_EDMA_VOXELS_OUT_CH                        (EDMA_DSS_TPCC_A_EVT_FREE_10 + 0)
#define DPC_OBJDET_DPU_MACRODOPP_BBF_EDMA_VOXELS_OUT_SHADOW                    (DPC_OBJDET_EDMA_SHADOW_BASE + 15)
#define DPC_OBJDET_DPU_MACRODOPP_BBF_EDMA_VOXELS_OUT_EVENT_QUE                 0

#define DPC_OBJDET_DPU_MACRODOPP_BBF_EDMA_VOXELS_MEAN_OUT_CH                   EDMA_DSS_TPCC_A_EVT_DSS_HW_ACC_CHANNEL_TRIGGER_4
#define DPC_OBJDET_DPU_MACRODOPP_BBF_EDMA_VOXELS_MEAN_OUT_SHADOW               (DPC_OBJDET_EDMA_SHADOW_BASE + 16)
#define DPC_OBJDET_DPU_MACRODOPP_BBF_EDMA_VOXELS_MEAN_OUT_EVENT_QUE            0

#define DPC_OBJDET_DPU_MACRODOPP_BBF_EDMA_HWA_EN_CH                           (EDMA_DSS_TPCC_A_EVT_FREE_11 + 0)
#define DPC_OBJDET_DPU_MACRODOPP_BBF_EDMA_HWA_EN_SHADOW                       (DPC_OBJDET_EDMA_SHADOW_BASE + 17)
#define DPC_OBJDET_DPU_MACRODOPP_BBF_EDMA_HWA_EN_EVENT_QUE                    0

//Macro Doppler FFT - multi-frame Doppler FFT
#define DPC_OBJDET_DPU_MACRODOPP_MULTI_FRM_EDMA_PHASE_IN_CH                   (EDMA_DSS_TPCC_A_EVT_FREE_12 + 0)
#define DPC_OBJDET_DPU_MACRODOPP_MULTI_FRM_EDMA_PHASE_IN_SHADOW               (DPC_OBJDET_EDMA_SHADOW_BASE + 18)
#define DPC_OBJDET_DPU_MACRODOPP_MULTI_FRM_EDMA_PHASE_IN_EVENT_QUE            0

#define DPC_OBJDET_DPU_MACRODOPP_MULTI_FRM_EDMA_PHASE_HOTSIG_CH               (EDMA_DSS_TPCC_A_EVT_FREE_13 + 0)
#define DPC_OBJDET_DPU_MACRODOPP_MULTI_FRM_EDMA_PHASE_HOTSIG_SHADOW           (DPC_OBJDET_EDMA_SHADOW_BASE + 19)
#define DPC_OBJDET_DPU_MACRODOPP_MULTI_FRM_EDMA_PHASE_HOTSIG_EVENT_QUE        0

#define DPC_OBJDET_DPU_MACRODOPP_MULTI_FRM_EDMA_PHASE_OUT_CH                  EDMA_DSS_TPCC_A_EVT_DSS_HW_ACC_CHANNEL_TRIGGER_5
#define DPC_OBJDET_DPU_MACRODOPP_MULTI_FRM_EDMA_PHASE_OUT_SHADOW              (DPC_OBJDET_EDMA_SHADOW_BASE + 20)
#define DPC_OBJDET_DPU_MACRODOPP_MULTI_FRM_EDMA_PHASE_OUT_EVENT_QUE           0

#define DPC_OBJDET_DPU_MACRODOPP_MULTI_FRM_EDMA_SYM_IN_CH                     (EDMA_DSS_TPCC_A_EVT_FREE_14 + 0)
#define DPC_OBJDET_DPU_MACRODOPP_MULTI_FRM_EDMA_SYM_IN_SHADOW                 (DPC_OBJDET_EDMA_SHADOW_BASE + 21)
#define DPC_OBJDET_DPU_MACRODOPP_MULTI_FRM_EDMA_SYM_IN_EVENT_QUE              0

#define DPC_OBJDET_DPU_MACRODOPP_MULTI_FRM_EDMA_SYM_HOTSIG_CH                 (EDMA_DSS_TPCC_A_EVT_FREE_15 + 0)
#define DPC_OBJDET_DPU_MACRODOPP_MULTI_FRM_EDMA_SYM_HOTSIG_SHADOW             (DPC_OBJDET_EDMA_SHADOW_BASE + 22)
#define DPC_OBJDET_DPU_MACRODOPP_MULTI_FRM_EDMA_SYM_HOTSIG_EVENT_QUE          0

#define DPC_OBJDET_DPU_MACRODOPP_MULTI_FRM_EDMA_SYM_OUT_CH                    EDMA_DSS_TPCC_A_EVT_DSS_HW_ACC_CHANNEL_TRIGGER_6
#define DPC_OBJDET_DPU_MACRODOPP_MULTI_FRM_EDMA_SYM_OUT_SHADOW                (DPC_OBJDET_EDMA_SHADOW_BASE + 23)
#define DPC_OBJDET_DPU_MACRODOPP_MULTI_FRM_EDMA_SYM_OUT_EVENT_QUE             0

//Average Macro Doppler FFT outputs
#define DPC_OBJDET_DPU_MACRODOPP_MULTI_FRM_EDMA_AVERAGE_IN_CH                     (EDMA_DSS_TPCC_A_EVT_FREE_16 + 0)
#define DPC_OBJDET_DPU_MACRODOPP_MULTI_FRM_EDMA_AVERAGE_IN_SHADOW                 (DPC_OBJDET_EDMA_SHADOW_BASE + 24)
#define DPC_OBJDET_DPU_MACRODOPP_MULTI_FRM_EDMA_AVERAGE_IN_EVENT_QUE              0

#define DPC_OBJDET_DPU_MACRODOPP_MULTI_FRM_EDMA_AVERAGE_HOTSIG_CH                 EDMA_DSS_TPCC_A_EVT_DSS_HW_ACC_CHANNEL_TRIGGER_7 //use as free channel
#define DPC_OBJDET_DPU_MACRODOPP_MULTI_FRM_EDMA_AVERAGE_HOTSIG_SHADOW             (DPC_OBJDET_EDMA_SHADOW_BASE + 25)
#define DPC_OBJDET_DPU_MACRODOPP_MULTI_FRM_EDMA_AVERAGE_HOTSIG_EVENT_QUE          0

#define DPC_OBJDET_DPU_MACRODOPP_MULTI_FRM_EDMA_AVERAGE_OUT_CH                    EDMA_DSS_TPCC_A_EVT_DSS_HW_ACC_CHANNEL_TRIGGER_8
#define DPC_OBJDET_DPU_MACRODOPP_MULTI_FRM_EDMA_AVERAGE_OUT_SHADOW                (DPC_OBJDET_EDMA_SHADOW_BASE + 26)
#define DPC_OBJDET_DPU_MACRODOPP_MULTI_FRM_EDMA_AVERAGE_OUT_EVENT_QUE             0

//Continuous chirping support
#define DPC_OBJDET_PROLONGED_BURSTING_IN_CH                            EDMA_DSS_TPCC_A_EVT_DSS_HW_ACC_CHANNEL_TRIGGER_9   //use as free channel
#define DPC_OBJDET_PROLONGED_BURSTING_IN_SHADOW_0                      (DPC_OBJDET_EDMA_SHADOW_BASE + 27)
#define DPC_OBJDET_PROLONGED_BURSTING_IN_SHADOW_1                      (DPC_OBJDET_EDMA_SHADOW_BASE + 28)
#define DPC_OBJDET_PROLONGED_BURSTING_IN_SHADOW_2                      (DPC_OBJDET_EDMA_SHADOW_BASE + 29)
#define DPC_OBJDET_PROLONGED_BURSTING_IN_EVENT_QUE                     0

//Timer driven architecture 
#define DPC_OBJDET_FRAME_START_CH                                       EDMA_DSS_TPCC_A_FRAMETIMER_FRAME_START
#define DPC_OBJDET_FRAME_START_GATE_ON_SHADOW_0                         (DPC_OBJDET_EDMA_SHADOW_BASE + 30)
#define DPC_OBJDET_FRAME_START_GATE_OFF_SHADOW_1                        (EDMA_DSS_TPCC_A_EVT_ADC_VALID_START)  //used as shadow
#define DPC_OBJDET_PROLONGED_BURSTING_IN_EVENT_QUE                      0

/*************************LVDS streaming EDMA resources*******************************/

/* CBUFF EDMA trigger channel */
#define MMW_LVDS_STREAM_CBUFF_EDMA_CH_0         EDMA_DSS_TPCC_A_EVT_DSS_CBUFF_DMA_REQ0

/*shadow CBUFF trigger channel*/
#define MMW_LVDS_STREAM_CBUFF_EDMA_SHADOW_CH_0   DPC_OBJDET_EDMA_SHADOW_BASE + 26 //EDMA_DSS_TPCC_B_EVT_FREE_0

#ifdef __cplusplus
}
#endif

#endif /* MMW_DEMO_RES_H */

