/**
 *   @file  macrodopplerproc.h
 *
 *   @brief
 *      Implements macrodoppler processing functionality.
 *
 *  \par
 *  NOTE:
 *      (C) Copyright 2025 Texas Instruments, Inc.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/**************************************************************************
 *************************** Include Files ********************************
 **************************************************************************/
#ifndef MACRODOP_PROC_H
#define MACRODOP_PROC_H

/* Standard Include Files. */
#include <stdint.h>
#include <stdlib.h>
#include <stddef.h>
#include <string.h>
#include <stdio.h>
#include <math.h>

/* mmWave SDK Driver/Common Include Files */
#include <drivers/hwa.h>

/* DPIF Components Include Files */
#include <datapath/dpif/dpif_detmatrix.h>
#include <datapath/dpif/dpif_radarcube.h>

/* mmWave SDK Data Path Include Files */
#include <datapath/dpif/dp_error.h>


/**
@defgroup DPU_DOA_EXTERNAL_FUNCTION            doaProc DPU External Functions
@ingroup DOA_PROC_DPU
@brief
*   The section has a list of all the exported API which the applications need to
*   invoke in order to use the doaProc DPU
*/
/**
@defgroup DPU_MACRODOPPROC_EXTERNAL_DATA_STRUCTURE      doaProc DPU External Data Structures
@ingroup DOA_PROC_DPU
@brief
*   The section has a list of all the data structures which are exposed to the application
*/
/**
@defgroup DPU_MACRODOPPROC_ERROR_CODE                   doaProc DPU Error Codes
@ingroup DOA_PROC_DPU
@brief
*   The section has a list of all the error codes which are generated by the doaProc DPU
*/
/**
@defgroup DPU_DOPPLERPROC_INTERNAL_FUNCTION            doaProc DPU Internal Functions
@ingroup DOA_PROC_DPU
@brief
*   The section has a list of all internal API which are not exposed to the external
*   applications.
*/
/**
@defgroup DPU_DOPPLERPROC_INTERNAL_DATA_STRUCTURE      doaProc DPU Internal Data Structures
@ingroup DOA_PROC_DPU
@brief
*   The section has a list of all internal data structures which are used internally
*   by the doaProc DPU module.
*/
/**
@defgroup DPU_DOPPLERPROC_INTERNAL_DEFINITION          doaProc DPU Internal Definitions
@ingroup DOA_PROC_DPU
@brief
*   The section has a list of all internal definitions which are used internally
*   by the doaProc DPU.
*/

#ifdef __cplusplus
extern "C" {
#endif

/** @addtogroup DPU_MACRODOPPROC_ERROR_CODE
 *  Base error code for the dopplerProc DPU is defined in the
 *  \include ti/datapath/dpif/dp_error.h
 @{ */

#define DP_ERRNO_MACRODOPP_PROC_BASE            (MMWAVE_ERRNO_DPU_BASE -1500)

/**
 * @brief   Error Code: Invalid argument
 */
#define DPU_MACRODOPPROC_EINVAL                  (DP_ERRNO_MACRODOPP_PROC_BASE-1)

/**
 * @brief   Error Code: Out of memory
 */
#define DPU_MACRODOPPROC_ENOMEM                  (DP_ERRNO_MACRODOPP_PROC_BASE-2)

/**
 * @brief   Error Code: DPU is in progress
 */
#define DPU_MACRODOPPROC_EINPROGRESS             (DP_ERRNO_MACRODOPP_PROC_BASE-3)

/**
 * @brief   Error Code: Out of HWA resources
 */
#define DPU_MACRODOPPROC_EHWARES                 (DP_ERRNO_MACRODOPP_PROC_BASE-4)

/**
 * @brief   Error Code: Semaphore creation failed
 */
#define DPU_MACRODOPPROC_ESEMA                   (DP_ERRNO_MACRODOPP_PROC_BASE-5)

/**
 * @brief   Error Code: Bad semaphore status 
 */
#define DPU_MACRODOPPROC_ESEMASTATUS             (DP_ERRNO_MACRODOPP_PROC_BASE-6)

/**
 * @brief   Error Code: Configure parameters exceed HWA memory bank size 
 */
#define DPU_MACRODOPPROC_EEXCEEDHWAMEM           (DP_ERRNO_MACRODOPP_PROC_BASE-7)

/**
 * @brief   Error Code: Unsupported radar cube format 
 */
#define DPU_MACRODOPPROC_ECUBEFORMAT             (DP_ERRNO_MACRODOPP_PROC_BASE-8)

/**
 * @brief   Error Code: Unsupported detection matrix format 
 */
#define DPU_MACRODOPPROC_EDETMFORMAT             (DP_ERRNO_MACRODOPP_PROC_BASE-9)

/**
 * @brief   Error Code: Insufficient detection matrix size
 */
#define DPU_MACRODOPPROC_EDETMSIZE               (DP_ERRNO_MACRODOPP_PROC_BASE-10)

/**
 * @brief   Error Code: Wrong window size
 */
#define DPU_MACRODOPPROC_EWINDSIZE               (DP_ERRNO_MACRODOPP_PROC_BASE-11)

/**
 * @brief   Error Code: Insufficient memory to save HWA param sets
 */
#define DPU_MACRODOPPROC_EHWA_PARAM_SAVE_LOC_SIZE (DP_ERRNO_MACRODOPP_PROC_BASE-12)

/**
 * @brief   Error Code: Not supported angle dim 1 (no elevation) and
 */
#define DPU_MACRODOPPROC_E_NOTSUPPORTED_ANGLE_DIM_ONE_AND_CPU_LOOP_CTRL (DP_ERRNO_MACRODOPP_PROC_BASE-13)

/**
 * @brief   Error Code: Doppler FFT size exceeded the limit. Maximum Doppler index is stored in array of type uint8_t.
 */
#define DPU_MACRODOPPROC_E_EXCEEDED_MAX_NUM_DOPPLER_BINS (DP_ERRNO_MACRODOPP_PROC_BASE-14)


/**
 * @brief   Maximum number of HWA param sets used by DPU.
 */
#define DPU_MACRODOPPROC_MAX_NUM_HWA_PARAMSET  16 //ToDo check this

/**
 * @brief   Number of HWA memory banks needed
 */
#define DPU_MACRODOPPROC_NUM_HWA_MEMBANKS  4 

/**
 * @brief   Disables first butterfly stage scaling
 */
#define DPU_MACRODOPPROC_FIRST_SCALING_DISABLED ((uint8_t)0U)

/**
 * @brief   Enables first butterfly stage scaling
 */
#define DPU_MACRODOPPROC_FIRST_SCALING_ENABLED ((uint8_t)1U)


/**
* @brief   Maximum number of zones
*/
#define DPU_MACRODOPPROC_MAX_NUM_ZONES 8


/**
 * @brief
 *  EDMA configuration parameters for chirp DC estimation for clutter removal
 *
 * @details
 *
 *  \ingroup DPU_MACRODOPPROC_EXTERNAL_DATA_STRUCTURE
 */
typedef struct macroDopplerProc_radCubeChirpDC_Edma_t
{
    /*! @brief  EDMA channels for clutter removal - radar cube DC estimation */
    DPEDMA_ChanCfg  edmaIn[2];
    DPEDMA_ChanCfg  edmaHotSig[2];
    DPEDMA_ChanCfg  edmaOut[2];
} macroDopplerProc_radCubeChirpDC_Edma;

/**
 * @brief
 *  EDMA configuration parameters for Bartlett beamforming
 *
 * @details
 *
 *  \ingroup DPU_MACRODOPPROC_EXTERNAL_DATA_STRUCTURE
 */
typedef struct macroDopplerProc_bartlettBeamforming_Edma_t
{
    DPEDMA_ChanCfg  edmaChirpsIn;
    DPEDMA_ChanCfg  edmaChirpsDCIn;
    DPEDMA_ChanCfg  edmaSteerVecIn;
    DPEDMA_ChanCfg  edmaHotSig;
    DPEDMA_ChanCfg  edmaVoxelsOut;
    DPEDMA_ChanCfg  edmaVoxelsMeanOut;
    DPEDMA_ChanCfg  edmaHwaEnable;
} macroDopplerProc_bartlettBeamforming_Edma;

/**
 * @brief
 *  EDMA configuration parameters for multi frame Doppler FFT
 *
 * @details
 *
 *  \ingroup DPU_MACRODOPPROC_EXTERNAL_DATA_STRUCTURE
 */
typedef struct macroDopplerProc_multiFrmDopplerFft_Edma_t
{
    DPEDMA_ChanCfg  edmaPhaseIn;
    DPEDMA_ChanCfg  edmaPhaseHotSig;
    DPEDMA_ChanCfg  edmaPhaseOut;

    DPEDMA_ChanCfg  edmaSymbIn;
    DPEDMA_ChanCfg  edmaSymbHotSig;
    DPEDMA_ChanCfg  edmaSymbOut;
} macroDopplerProc_multiFrmDopplerFft_Edma;


/**
 * @brief
 *  EDMA configuration parameters for multi frame Doppler FFT
 *
 * @details
 *
 *  \ingroup DPU_MACRODOPPROC_EXTERNAL_DATA_STRUCTURE
 */
typedef struct macroDopplerProc_averageMacroDopplerFft_Edma_t
{
    DPEDMA_ChanCfg  edmaIn;
    DPEDMA_ChanCfg  edmaHotSig;
    DPEDMA_ChanCfg  edmaOut;
} macroDopplerProc_averageMacroDopplerFft_Edma;



/**
 * @brief
 *  doaProc DPU statistics
 *
 * @details
 *  The structure is used to hold the statistics of the DPU 
 *
 *  \ingroup DPU_MACRODOPPROC_EXTERNAL_DATA_STRUCTURE
 */
typedef struct DPU_MacroDopplerProc_Stats_t
{

    /*! @brief For HWA version of the DPU: total processing time including EDMA transfers.\n
               For DSP version of the DPU: total processing time excluding EDMA transfers.*/
    uint32_t            processingTime;
    
    /*! @brief time spent waiting for EDMA transfers. Valid only for DSP version of DPU.*/
    uint32_t            waitTime;
}DPU_MacroDopplerProc_Stats;




/*!
 *  @brief   Handle for Doppler Processing DPU.
 */
typedef void*  DPU_MacroDopplerProc_Handle;

/**
 * @brief
 *  dopplerProc DPU initial configuration parameters
 *
 * @details
 *  The structure is used to hold the DPU initial configurations.
 *
 *  \ingroup DPU_MACRODOPPROC_EXTERNAL_DATA_STRUCTURE
 */
typedef struct DPU_MacroDopplerProc_InitCfg_t
{
    HWA_Handle  hwaHandle;
    
}DPU_MacroDopplerProc_InitParams;



/**
 * @brief    Maximum number of antenna elements in 2D virtual antenna array (maximum value of the product numRows*numCol)
 *
 */
#define DPU_DOA_PROC_MAX_2D_ANT_ARRAY_ELEMENTS 16

/**
 * @brief
 *  Structure for the HWA Params save location
 *
 *
 *  \ingroup DPU_MACRODOPPROC_EXTERNAL_DATA_STRUCTURE
 */
typedef struct DPU_MacroDopplerProc_HwaParamSaveLoc_t
{
    /*! @brief  Pointer to save location for HWA PARAM sets */
    void        *data;

    /*! @brief  Size of the save location for HWA PARAM sets in Bytes*/
    uint32_t    sizeBytes;
} DPU_MacroDopplerProc_HwaParamSaveLoc;

/**
 * @brief
 *  dopplerProc DPU HWA configuration parameters
 *
 * @details
 *  The structure is used to hold the HWA configuration parameters
 *  for the Doppler Processing DPU
 *
 *  \ingroup DPU_MACRODOPPROC_EXTERNAL_DATA_STRUCTURE
 */
typedef struct DPU_MacroDopplerProc_HwaCfg_t
{
    /*! @brief Indicates if HWA window is symmetric or non-symmetric.
        Use HWA macro definitions for symmetric/non-symmetric.
    */
    uint8_t     winSym;

    /*!  @brief Doppler FFT window size in bytes. 
         This is the number of coefficients to be programmed in the HWA for the windowing
         functionality. The size is a function of numDopplerChirps as follows:\n
         If non-symmetric window is selected: windowSize = numDopplerChirps * sizeof(int32_t) \n
         If symmetric window is selected and numDopplerChirps is even:
         windowSize = numDopplerChirps * sizeof(int32_t) / 2 \n
         If symmetric window is selected and numDopplerChirps is odd:
         windowSize = (numDopplerChirps + 1) * sizeof(int32_t) / 2        
    */
    uint32_t    windowSize;

    /*! @brief Pointer to Doppler FFT window coefficients. */
    int32_t     *window;

    /*! @brief HWA window RAM offset in number of samples. */
    uint32_t    winRamOffset;
    
    /*! @brief Indicates if HWA should enable butterfly scaling (divide by 2) of the 
         first radix-2 stage. Depending on the window definition, 
         user may want to skip the first stage scaling in order to avoid signal degradation.\n
         Options are:\n
         Disable first stage scaling: firstStageScaling = @ref DPU_MACRODOPPROC_FIRST_SCALING_DISABLED \n
         Enable first stage scaling: firstStageScaling = @ref DPU_MACRODOPPROC_FIRST_SCALING_ENABLED \n
         Note: All other butterfly stages have the scaling enabled. 
         This option applies only for the first stage.\n
    */
    uint8_t     firstStageScaling;

    /*! @brief Number of HWA paramsets reserved for the Doppler DPU. 
         The number of HWA paramsets required by this DPU is a function of the number of TX antennas 
         used in the configuration:\n 
         numParamSets = 2 x (Number of TX antennas) + 2\n
         The DPU will use numParamSets consecutively, starting from paramSetStartIdx.\n
    */     
    uint8_t     numParamSets;
    
    /*! @brief HWA paramset Start index.  
         Application has to ensure that paramSetStartIdx is such that \n
        [paramSetStartIdx, paramSetStartIdx + 1, ... (paramSetStartIdx + numParamSets - 1)] \n
        is a valid set of HWA paramsets.\n
    */
    uint32_t    paramSetStartIdx;

    /*! @brief HWA data input paramset dma trigger source channel
    */
    uint8_t     dmaTriggerSource[2];


    /*! @brief HWA Params save location
    */
    DPU_MacroDopplerProc_HwaParamSaveLoc hwaParamsSaveLoc;


}DPU_MacroDopplerProc_HwaCfg;

/*!
 *  @brief    Maximum peaks filled by HWA statistics block
 *
 *  \ingroup DPU_MACRODOPPROC_EXTERNAL_DATA_STRUCTURE
 *
 */
typedef volatile struct DPU_MacroDopplerProc_HwaMaxOutput_t
{
    uint32_t   maxInd;      /*!< @brief Maximum peak index position */
    uint32_t   peak;        /*!< @brief Maximum peak value */
}  DPU_MacroDopplerProc_HwaMaxOutput;


/**
 * @brief
 *  dopplerProc DPU EDMA configuration parameters
 *
 * @details
 *  The structure is used to hold the EDMA configuration parameters
 *  for the Doppler Processing DPU
 *
 *  \ingroup DPU_MACRODOPPROC_EXTERNAL_DATA_STRUCTURE
 */
typedef struct DPU_MacroDopplerProc_EdmaCfg_t
{
    /*! @brief  EDMA driver handle. */
    EDMA_Handle edmaHandle;
    uint32_t    edmaInstanceId;
    
    /*! @brief  EDMA configuration for Input data (Radar cube -> HWA memory). */
    macroDopplerProc_radCubeChirpDC_Edma edmaChirpDC;

    macroDopplerProc_bartlettBeamforming_Edma edmaBeamFrm;

    macroDopplerProc_multiFrmDopplerFft_Edma edmaMultiFrmDopFft;

    macroDopplerProc_averageMacroDopplerFft_Edma edmaAverageMacroDopFft;

}DPU_MacroDopplerProc_EdmaCfg;

/**
 * @brief
 *  Doppler DPU HW configuration parameters
 *
 * @details
 *  The structure is used to hold the  HW configuration parameters
 *  for the Doppler DPU
 *
 *  \ingroup DPU_MACRODOPPROC_EXTERNAL_DATA_STRUCTURE
 */
typedef struct DPU_MacroDopplerProc_HW_Resources_t
{
    /*! @brief     EDMA Handle */
    //EDMA_Handle         edmaHandle;

    /*! @brief  EDMA configuration */
    DPU_MacroDopplerProc_EdmaCfg edmaCfg;
    
    /*! @brief  HWA configuration */
    DPU_MacroDopplerProc_HwaCfg  hwaCfg;
    
    /*! @brief  Radar Cube */
    DPIF_RadarCube radarCube;
    
    /*! @brief  Detection matrix */
    DPIF_DetMatrix detMatrix;

    /*! @brief  Doppler index matrix */
    DPIF_DetMatrix dopplerIndexMatrix;

    /*! @brief  pointer to radar cube DC values */
    cmplx32ImRe_t *radCubeDCvalue;

    /*! @brief  Voxel symbols ping/pong output */
    cmplx32ImRe_t *voxelSymOut;

    /*! @brief  Voxel symbols mean ping/pong output */
    cmplx32ImRe_t *voxelSymMeanOut;

}DPU_MacroDopplerProc_HW_Resources;

/**
 * @brief Range Bias and rx channel gain/phase compensation configuration.
 *
 *
 *  \ingroup    DPU_MACRODOPPROC_EXTERNAL_DATA_STRUCTURE
 *
 */
typedef struct DPU_MacroDopplerProc_compRxChannelBiasCfg_t
{

    /*! @brief  Compensation for range estimation bias in meters */
    float rangeBias;

    /*! @brief  Compensation for Rx channel phase bias in Q20 format.
     *          The order here is like x[tx][rx] where rx order is 0,1,....SYS_COMMON_NUM_RX_CHANNEL-1
     *          and tx order is 0, 1,...,SYS_COMMON_NUM_TX_ANTENNAS-1 */
    cmplx32ReIm_t rxChPhaseComp[SYS_COMMON_NUM_TX_ANTENNAS * SYS_COMMON_NUM_RX_CHANNEL];

} DPU_MacroDopplerProc_compRxChannelBiasCfg;

/**
 * @brief Range Bias and rx channel gain/phase compensation configuration.
 *
 *
 *  \ingroup    DPU_MACRODOPPROC_EXTERNAL_DATA_STRUCTURE
 *
 */
typedef struct DPU_MacroDopplerProc_zoneParam_t
{

    /*! @brief  Number of steering vectors */
    uint16_t    numSteerVec;

    /*! @brief  Steering vector offset */
    uint16_t    steerVecOffset;

} DPU_MacroDopplerProc_zoneParam;
/**
 * @brief
 *  Doppler DPU static configuration parameters
 *
 * @details
 *  The structure is used to hold the static configuration parameters
 *  for the Doppler DPU. The following conditions must be satisfied:
 *
 *    @verbatim
      numTxAntennas * numRxAntennas * numDopplerChirps * sizeof(cmplx16ImRe_t) <= 16 KB (one HWA memory bank)
      numTxAntennas * numRxAntennas * numDopplerBins * sizeof(uint16_t) <= 16 KB (one HWA memory bank)
      @endverbatim
 *
 *  \ingroup DPU_MACRODOPPROC_EXTERNAL_DATA_STRUCTURE
 */
typedef struct DPU_MacroDopplerProc_StaticConfig_t
{
    /*! @brief  Number of transmit antennas */
    uint8_t     numTxAntennas;
    
    /*! @brief  Number of receive antennas */
    uint8_t     numRxAntennas;
    
    /*! @brief  Number of virtual antennas */
    uint8_t     numVirtualAntennas; 
    
    /*! @brief  Number of range bins */
    uint16_t    numRangeBins;

    /*! @brief  Number of Doppler chirps. */
    uint16_t    numDopplerChirps;
    /*! @brief  Number of Doppler bins */
    uint16_t    numDopplerBins;

    /*! @brief  Number of virtual chirps per frame */
    uint16_t    numVirtChirpsPerFrame;
    /*! @brief  Number of virtual chirps per sliding window (number of chirps per radar cube) */
    uint16_t    numVirtChirpsPerSlidingWindow;
    /*! @brief  Number of frames per sliding window */
    uint16_t    numFramesPerSlidingWindow;

    /*! @brief  frame counter within sliding window */
    uint16_t    frmCntrInSlidingWindowInitVal;



////////////////////////////////////////////////////////////////
    
    /*! @brief  Log2 of number of Doppler bins */
    uint8_t     log2NumDopplerBins;
    
    /*! @brief   Static Clutter Removal Cfg */
    bool        isStaticClutterRemovalEnabled;

    /*! @brief   Range Bias and rx channel gain/phase compensation enable flag */
    bool        isRxChGainPhaseCompensationEnabled;

    /*! @brief   Range Bias and rx channel gain/phase compensation configuration */
    DPU_MacroDopplerProc_compRxChannelBiasCfg compRxChanCfg;

    uint16_t numAntRow;
    uint16_t numAntCol;

    //Beamforming params
    uint16_t        numZones;
    uint16_t        steerVecLen;
    uint16_t        numChirpAvg;
    uint16_t        chirpAvgStartIdx;
    uint16_t        chirpAvgStep;
    uint16_t        numSteerVec;
    cmplx32ReIm_t   *steerVec;
    uint16_t        *rangeBinVec;
    DPU_MacroDopplerProc_zoneParam zoneParam[DPU_MACRODOPPROC_MAX_NUM_ZONES];
    uint16_t        multiFrmDopplerFftSize;
    uint16_t        multiFrmDelayLineLen;
    uint16_t        multiFrmActualDelayLineLen;
    int16_t         *phaseMultFrmDelayLine;
    int16_t         *previousVoxelPhaseArray;
    cmplx32ImRe_t   *symbMultiFrmDelayLine;

    uint32_t   *phaseMultiFrmDoppOut;
    uint32_t   *symbMultiFrmDoppOut;
    uint32_t   *averageSymbMultiFrmDoppOut;



    /*! @brief     Load HWA params sets before execution */
    bool loadHwaParamSetsBeforeExec;

    /*! @brief     Enable/disable Macro (multiframe) Doppler FFT Window */
    bool multiFrmFftWindowEnabled;

    /*! @brief     Enable/disable multi-frame phase Doppler FFT */
    bool multiFrmPhaseDopFftEnabled;

}DPU_MacroDopplerProc_StaticConfig;

/**
 * @brief
 *  dopplerProc DPU configuration parameters
 *
 * @details
 *  The structure is used to hold the configuration parameters
 *  for the Doppler Processing removal DPU
 *
 *  \ingroup DPU_MACRODOPPROC_EXTERNAL_DATA_STRUCTURE
 */
typedef struct DPU_MacroDopplerProc_Config_t
{
    /*! @brief HW resources. */
    DPU_MacroDopplerProc_HW_Resources  hwRes;
    
    /*! @brief Static configuration. */
    DPU_MacroDopplerProc_StaticConfig  staticCfg;
    
}DPU_MacroDopplerProc_Config;


/**
 * @brief
 *  DPU processing output parameters
 *
 * @details
 *  The structure is used to hold the output parameters DPU processing
 *
 *  \ingroup DPU_MACRODOPPROC_EXTERNAL_DATA_STRUCTURE
 */
typedef struct DPU_MacroDopplerProc_OutParams_t
{
    /*! @brief DPU statistics */
    DPU_MacroDopplerProc_Stats  stats;
}DPU_MacroDopplerProc_OutParams;


DPU_MacroDopplerProc_Handle DPU_MacroDopplerProc_init(DPU_MacroDopplerProc_InitParams *initCfg, int32_t* errCode);
int32_t DPU_MacroDopplerProc_process(DPU_MacroDopplerProc_Handle handle, DPU_MacroDopplerProc_OutParams *outParams);
int32_t DPU_MacroDopplerProc_deinit(DPU_MacroDopplerProc_Handle handle);
int32_t DPU_MacroDopplerProc_config(DPU_MacroDopplerProc_Handle handle, DPU_MacroDopplerProc_Config *cfg);
int32_t DPU_MacroDopplerProc_GetNumUsedHwaParamSets(DPU_MacroDopplerProc_Handle handle, uint8_t *numUsedHwaParamSets);

#if 0
int32_t DPU_MacroDopplerProc_control
(
   DPU_MacroDopplerProc_Handle handle,
   DPU_MacroDopplerProc_Cmd cmd,
   void *arg,
   uint32_t argSize
);
#endif


#ifdef __cplusplus
}
#endif

#endif
